# Generated by Django 5.1.6 on 2025-02-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(db_index=True, max_length=500, unique=True),
        ),
    ]
